# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Semi-Binary Build
on:
  pull_request:
  push:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * *'


jobs:
  semi-binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, jazzy, humble]
        ROS_REPO: [testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: control_toolbox.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: ros2-master
