# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Humble - Semi-Binary Build
on:
  pull_request: &event
    branches:
      - humble
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/humble-semi-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'control_toolbox.humble.repos'
      - '**.xml'
  push: *event
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  semi-binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: humble
      ros_repo: testing
      upstream_workspace: control_toolbox.humble.repos
      ref_for_scheduled_build: humble
