# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Rolling - Downstream Build
on:
  pull_request:
    branches:
      - ros2-master
  push:
    branches:
      - ros2-master

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  build-downstream:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: testing
      ref_for_scheduled_build: ros2-master
      not_test_build: true
      upstream_workspace: control_toolbox.${{ matrix.ROS_DISTRO }}.repos
      # we test the downstream packages, which are part of our organization
      downstream_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      not_test_downstream: false
