name: Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    strategy:
      fail-fast: false
      matrix:
        include:
        - ROS_DISTRO: jazzy
          CONTAINER: ubuntu:24.04
          OS_NAME: ubuntu-latest
        - ROS_DISTRO: rolling
          CONTAINER: ubuntu:24.04
          OS_NAME: ubuntu-latest
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ref: ros2-master
      ros2_repo_branch: ${{ matrix.ROS_DISTRO }}
      os_name: ${{ matrix.OS_NAME }}
      container: ${{ matrix.CONTAINER }}
